[package]
name = "twitch-play-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
regex = "1"
lazy_static = "1.4.0"
tfc = "0.6.1"
